// Package oapistub provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.10.1 DO NOT EDIT.
package oapistub

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// エラー情報
type ErrorDescription map[string]interface{}

// Message defines model for Message.
type Message struct {
	CreatedAt time.Time `json:"created_at"`
	Id        int64     `json:"id"`
	Message   string    `json:"message"`
	Name      string    `json:"name"`
	UpdatedAt time.Time `json:"updated_at"`
}

// NewMessage defines model for NewMessage.
type NewMessage struct {
	Message string `json:"message"`
	Name    string `json:"name"`
}

// Organization
type Organization struct {
	// Organization ID
	Id string `json:"id"`

	// Organization の名前
	Name string `json:"name"`
}

// OrganizationId defines model for organizationId.
type OrganizationId string

// CreateMessagesSuccess defines model for CreateMessagesSuccess.
type CreateMessagesSuccess struct {
	Id int64 `json:"id"`
}

// ErrInternal defines model for ErrInternal.
type ErrInternal struct {
	// エラー情報
	Error ErrorDescription `json:"error"`
}

// ErrNotFound defines model for ErrNotFound.
type ErrNotFound struct {
	// エラー情報
	Error ErrorDescription `json:"error"`
}

// ErrUnauthorized defines model for ErrUnauthorized.
type ErrUnauthorized struct {
	// エラー情報
	Error ErrorDescription `json:"error"`
}

// Message 一覧の成功レスポンス
type GetMessagesSuccess struct {
	// Message の配列
	Messages []Message `json:"messages"`
}

// Organization 取得の成功レスポンス
type GetOrganizationSuccess struct {
	// Organization
	Organization Organization `json:"organization"`
}

// Organization 一覧の成功レスポンス
type ListOrganizationsSuccess struct {
	// Organization の配列
	Organizations []Organization `json:"organizations"`
}

// CreateMessageJSONBody defines parameters for CreateMessage.
type CreateMessageJSONBody NewMessage

// CreateMessageJSONRequestBody defines body for CreateMessage for application/json ContentType.
type CreateMessageJSONRequestBody CreateMessageJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ヘルスチェック
	// (GET /healthcheck)
	Healthcheck(ctx echo.Context) error
	// Get all messages
	// (GET /messages)
	GetMessages(ctx echo.Context) error
	// Create a new message
	// (POST /messages)
	CreateMessage(ctx echo.Context) error
	// Organization 一覧
	// (GET /organizations)
	ListOrganizations(ctx echo.Context) error
	// Organization 取得
	// (GET /organizations/{organizationId})
	GetOrganization(ctx echo.Context, organizationId OrganizationId) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// Healthcheck converts echo context to params.
func (w *ServerInterfaceWrapper) Healthcheck(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.Healthcheck(ctx)
	return err
}

// GetMessages converts echo context to params.
func (w *ServerInterfaceWrapper) GetMessages(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetMessages(ctx)
	return err
}

// CreateMessage converts echo context to params.
func (w *ServerInterfaceWrapper) CreateMessage(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.CreateMessage(ctx)
	return err
}

// ListOrganizations converts echo context to params.
func (w *ServerInterfaceWrapper) ListOrganizations(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.ListOrganizations(ctx)
	return err
}

// GetOrganization converts echo context to params.
func (w *ServerInterfaceWrapper) GetOrganization(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "organizationId" -------------
	var organizationId OrganizationId

	err = runtime.BindStyledParameterWithLocation("simple", false, "organizationId", runtime.ParamLocationPath, ctx.Param("organizationId"), &organizationId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter organizationId: %s", err))
	}

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetOrganization(ctx, organizationId)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/healthcheck", wrapper.Healthcheck)
	router.GET(baseURL+"/messages", wrapper.GetMessages)
	router.POST(baseURL+"/messages", wrapper.CreateMessage)
	router.GET(baseURL+"/organizations", wrapper.ListOrganizations)
	router.GET(baseURL+"/organizations/:organizationId", wrapper.GetOrganization)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RYXW/cRBT9K9bAoxO76aak+wZpSSPRtFLDU7RCg3d27Y3tccfjpNvIUm1TlDaNkkaC",
	"lAfUIqGmBJQKARIRXz9muiH8CzT22uuv3fUmoKhv3vXMnXPPnXvmjDeAgg0Lm8ikNqhvAAsSaCCKSPgL",
	"kzY0tfuQathcbPJ/mshWiGbxP0Ad3Eq9FxavARFo/G8LUhWIwIQGAvV8EBEQdNfRCGqCOiUOEoGtqMiA",
	"PDrtWnyGTYlmtoHrunywbWHTRiGeeYIgRTeRbcM2su84ioLs8IWCTYpMyh+hZemaEq4mdWwOcyO1gkWw",
	"hQjVonhamFMLEwNSUAeaSa/UgBjD0EyK2oiACEaMeYXPaiSD8KcdpNAIa5acPkzh5PEXf7/662Rzt/f4",
	"OQt+YP4xC75mwU/MPwauCK4TsmhSREyonyMTRAgm/OFdglqgDt6RBnWVokm2dJ0PupYCmc8silIlOeb/",
	"woLfWbDL/Fcs+I4/e0e9Fz/3djeZd1Se5hKmH2LHbL5NaQaHzP+DZ+cfM+/J6cst5n3LvC3mP2LeIfM+",
	"G5PyxyZ0qIqJdh+9TWmfHm73dl4z74B521GeIRGvebF5kpvM3+vt7DPv6ZvfnjHvKfOejyJiAdHz9Gx5",
	"W7359cHpywPmHZV3lpij0OgDGB6QeUf/PNzube5zGaPIsMcR3p/IM+wzCgmB3QLvydKTqMaY9CJW0/pb",
	"nVl0DxqWHlERRedPa1B3UF70Y5EEiqLNylcJuYJnO/qMimc6V+WBxBtdZyrccDyfYYXLHBa9nS97f+5X",
	"rl4e06iypNcp1CITqEo9JkHtiuAjzc5Uxf5fymKD+spEhWlUr8yEfZWDNTL0xB2WLeWYNssimbi24xou",
	"4S9EXRDbQubJwXgSPOy9+JHbCo3qHFBhbh6qCO5NpXaDy3/bFFu61lZp0pKrLauzOtdCjqw2ayG+WJAK",
	"54cS+qbmJ5Bm/E4TUjRFNQMNEMTWS6zqjcRY3kr8W7wNS144VnNCREUT1g8/QCCmE82sUdwNIlhC60MJ",
	"O0NOOXw5aGUAbuVEbfjmLHSdVsmMD4U+ukd7u9u9R9sTVKAx2Ns51GfZ163aTAe/16117zqd9f6Zopkt",
	"HEsoVMKxfYW72XWwKcxjYk2DQoMvYOHG8vJt4Q4ia4gIy8iwdEiR8P7txVQ/jh61hogdRZOn5elLfBFs",
	"IRNaGqiDy9Py9GVeHUjVsDCSiqBOVUVFyir/3Ua0RBqCZyz4PpQXj/kHLAhCb7V3+s0T5n3OHvggXIMk",
	"9y5wIxU1dyeakWvFFZawMN8/bVwR1ORLw5Q2CSXl3aorgllZrjQvub+EIukYBiTdYWly3mGbH2CA9okG",
	"DT5PSju0Pm1ZElI2skhCBaQlNvTiyFlAVIC6LiRZuyKwsF2SdubS278+I5t+gJvdiWz0qIM2pYVu8dpd",
	"id3yu/nFERzhEaBgovWY5XCIVLAspU2aVUV/L/YHXzF/q6xFC87vTHt0qH+8OCJLXNLwJs5wK21kv/24",
	"lcmOjfYwsnN3n7PKQdn96RxE1yIpHjsv+RDyHxcnYq28OGLm095K+YqDIVLuq50bltcOT8hofraAOlag",
	"rnL9EoFDdFAHKqVWXZKSF/U5eU4GbiNBlxzhCUq34f4bAAD//0TMzDuQFAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
