/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 保険加入者の居住情報
 * @export
 * @interface Address
 */
export interface Address {
    /**
     * 郵便番号（ハイフンなし）
     * @type {string}
     * @memberof Address
     */
    'postal_code': string;
    /**
     * 都道府県
     * @type {string}
     * @memberof Address
     */
    'prefecture': string;
    /**
     * 市町村
     * @type {string}
     * @memberof Address
     */
    'city': string;
    /**
     * 番地
     * @type {string}
     * @memberof Address
     */
    'street': string;
    /**
     * 建物名・部屋番号
     * @type {string}
     * @memberof Address
     */
    'building'?: string;
}

