/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';

/**
 * 保険加入者情報
 * @export
 * @interface Contractor
 */
export interface Contractor {
    /**
     * 氏名
     * @type {string}
     * @memberof Contractor
     */
    'name': string;
    /**
     * 氏名フリガナ
     * @type {string}
     * @memberof Contractor
     */
    'kana': string;
    /**
     * 生年月日（unixtimestamp utc）
     * @type {number}
     * @memberof Contractor
     */
    'date_of_birth': number;
    /**
     * 電話番号（ハイフンなし）
     * @type {string}
     * @memberof Contractor
     */
    'phone_number': string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof Contractor
     */
    'email': string;
    /**
     * 
     * @type {Address}
     * @memberof Contractor
     */
    'address': Address;
}

