/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 保険加入時に購入した端末の情報
 * @export
 * @interface Device
 */
export interface Device {
    /**
     * 購入デバイスのIMEI
     * @type {string}
     * @memberof Device
     */
    'imei': string;
    /**
     * 購入デバイスの名称
     * @type {string}
     * @memberof Device
     */
    'name': string;
}

