/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InsuranceContractor } from './insurance-contractor';

/**
 * 自身の保険契約者としての情報取得レスポンス
 * @export
 * @interface GetMyInsuranceContractorResponse
 */
export interface GetMyInsuranceContractorResponse {
    /**
     * 
     * @type {InsuranceContractor}
     * @memberof GetMyInsuranceContractorResponse
     */
    'insurance_contractor': InsuranceContractor;
}

