/* tslint:disable */
/* eslint-disable */
/**
 * TEMPLATE API
 * TEMPLATE API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Organization } from './organization';

/**
 * 保険契約者情報検索レスポンス
 * @export
 * @interface GetOrganizationsResponse
 */
export interface GetOrganizationsResponse {
    /**
     * 組織の配列
     * @type {Array<Organization>}
     * @memberof GetOrganizationsResponse
     */
    'organizations': Array<Organization>;
}

