/* tslint:disable */
/* eslint-disable */
/**
 * Go HTTP Server Template API
 * Go HTTP Server Template API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Healthcheck401Response
 */
export interface Healthcheck401Response {
    /**
     * エラー情報
     * @type {object}
     * @memberof Healthcheck401Response
     */
    'error': object;
}

