/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';
import { Device } from './device';

/**
 * 保険加入者
 * @export
 * @interface InsuranceContractor
 */
export interface InsuranceContractor {
    /**
     * 個別の保険契約者を識別するためのid(xid)
     * @type {string}
     * @memberof InsuranceContractor
     */
    'id': string;
    /**
     * コンバージョンid(xid)
     * @type {string}
     * @memberof InsuranceContractor
     */
    'conversion_id': string;
    /**
     * 氏名
     * @type {string}
     * @memberof InsuranceContractor
     */
    'name': string;
    /**
     * 氏名フリガナ
     * @type {string}
     * @memberof InsuranceContractor
     */
    'kana': string;
    /**
     * 登録店舗名
     * @type {string}
     * @memberof InsuranceContractor
     */
    'store_name': string;
    /**
     * 電話番号（ハイフンなし）
     * @type {string}
     * @memberof InsuranceContractor
     */
    'phone_number': string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof InsuranceContractor
     */
    'email': string;
    /**
     * 
     * @type {Address}
     * @memberof InsuranceContractor
     */
    'address': Address;
    /**
     * 
     * @type {Device}
     * @memberof InsuranceContractor
     */
    'device': Device;
    /**
     * コーティングを貼り付けた状態の購入デバイスの画像url
     * @type {string}
     * @memberof InsuranceContractor
     */
    'coating_image_url': string;
    /**
     * 購入レシートの画像url
     * @type {string}
     * @memberof InsuranceContractor
     */
    'receipt_image_url': string;
    /**
     * キャンセルされているかどうか
     * @type {boolean}
     * @memberof InsuranceContractor
     */
    'canceled': boolean;
    /**
     * キャンセル日時
     * @type {number}
     * @memberof InsuranceContractor
     */
    'canceled_at'?: number;
    /**
     * 契約日時(unix timestamp)
     * @type {number}
     * @memberof InsuranceContractor
     */
    'contracted_at': number;
    /**
     * メモ
     * @type {string}
     * @memberof InsuranceContractor
     */
    'memo'?: string;
}

