/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 写真アップロード用url発行要求レスポンス
 * @export
 * @interface IssueUploadImageUrlsResponse
 */
export interface IssueUploadImageUrlsResponse {
    /**
     * コーティングを貼り付けた状態の購入デバイス画像のアップロードurl。
     * @type {number}
     * @memberof IssueUploadImageUrlsResponse
     */
    'coating_image_url'?: number;
    /**
     * コーティングを貼り付けた状態の購入デバイス画像のアップロードurl。
     * @type {number}
     * @memberof IssueUploadImageUrlsResponse
     */
    'receipt_image_url'?: number;
}

