/* tslint:disable */
/* eslint-disable */
/**
 * TEMPLATE API
 * TEMPLATE API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import { Organization } from './organization';

/**
 * 組織一覧レスポンス
 * @export
 * @interface ListOrganizationsResponse
 */
export interface ListOrganizationsResponse {
    /**
     * 組織の配列
     * @type {Array<Organization>}
     * @memberof ListOrganizationsResponse
     */
    'organizations': Array<Organization>;
}

