/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Model401
 */
export interface Model401 {
    /**
     * コード
     * @type {number}
     * @memberof Model401
     */
    'code': number;
    /**
     * メッセージ
     * @type {string}
     * @memberof Model401
     */
    'message'?: string;
}

