/* tslint:disable */
/* eslint-disable */
/**
 * TEMPLATE API
 * TEMPLATE API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Model500
 */
export interface Model500 {
    /**
     * コード
     * @type {number}
     * @memberof Model500
     */
    'code': number;
    /**
     * メッセージ
     * @type {string}
     * @memberof Model500
     */
    'message'?: string;
}

