/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 写真アップロード用url発行リクエスト
 * @export
 * @interface NewUploadImageUrlsRequest
 */
export interface NewUploadImageUrlsRequest {
    /**
     * アップロード予定のコーティングを貼り付けた状態の購入デバイス画像のサイズ(byte)。最大20mb(20971520byte)まで。
     * @type {number}
     * @memberof NewUploadImageUrlsRequest
     */
    'coating_image_size': number;
    /**
     * コーティング購入レシート画像のサイズ(byte)。最大20mb(20971520byte)まで。
     * @type {number}
     * @memberof NewUploadImageUrlsRequest
     */
    'receipt_image_size': number;
}

