/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Contractor } from './contractor';
import { Device } from './device';

/**
 * 保険契約情報登録リクエスト
 * @export
 * @interface NewInsuranceContractRequest
 */
export interface NewInsuranceContractRequest {
    /**
     * 
     * @type {Device}
     * @memberof NewInsuranceContractRequest
     */
    'device': Device;
    /**
     * 
     * @type {Contractor}
     * @memberof NewInsuranceContractRequest
     */
    'contractor': Contractor;
    /**
     * コーティングを貼り付けた状態の購入デバイスの画像url
     * @type {string}
     * @memberof NewInsuranceContractRequest
     */
    'coating_image_url': string;
    /**
     * 購入レシートの画像url
     * @type {string}
     * @memberof NewInsuranceContractRequest
     */
    'receipt_image_url': string;
    /**
     * reppleサイトから付与されるアフィリエイトid
     * @type {string}
     * @memberof NewInsuranceContractRequest
     */
    'affiliate_id': string;
    /**
     * ログインに使用する password
     * @type {string}
     * @memberof NewInsuranceContractRequest
     */
    'password': string;
}

