/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * csvダウンロードURL発行リクエスト
 * @export
 * @interface NewCsvDownloadUrlRequest
 */
export interface NewCsvDownloadUrlRequest {
    /**
     * 対象の年月(JST, YYYY-MM)
     * @type {string}
     * @memberof NewCsvDownloadUrlRequest
     */
    'year_month': string;
}

