/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * csvダウンロードURL発行レスポンス
 * @export
 * @interface NewCsvDownloadUrlResponse
 */
export interface NewCsvDownloadUrlResponse {
    /**
     * 
     * @type {string}
     * @memberof NewCsvDownloadUrlResponse
     */
    'url': string;
}

