/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Address } from './address';
import { Device } from './device';

/**
 * 保険契約情報登録リクエスト
 * @export
 * @interface NewInsuranceContractorRequest
 */
export interface NewInsuranceContractorRequest {
    /**
     * コンバージョンid(xid)
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'conversion_id': string;
    /**
     * 氏名
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'name': string;
    /**
     * 氏名フリガナ
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'kana': string;
    /**
     * 登録店舗名
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'store_name': string;
    /**
     * 電話番号(ハイフンなし)
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'phone_number': string;
    /**
     * メールアドレス
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'email': string;
    /**
     * パスワード
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'password': string;
    /**
     * 
     * @type {Address}
     * @memberof NewInsuranceContractorRequest
     */
    'address': Address;
    /**
     * 
     * @type {Device}
     * @memberof NewInsuranceContractorRequest
     */
    'device': Device;
    /**
     * コーティングを貼り付けた状態の購入デバイスの画像urlのuuid
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'coating_image_uuid': string;
    /**
     * 購入レシートの画像urlのuuid
     * @type {string}
     * @memberof NewInsuranceContractorRequest
     */
    'receipt_image_uuid': string;
}

