/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Token } from './token';

/**
 * oauth レスポンス
 * @export
 * @interface OauthResponse
 */
export interface OauthResponse {
    /**
     * 
     * @type {Token}
     * @memberof OauthResponse
     */
    'token': Token;
}

