/* tslint:disable */
/* eslint-disable */
/**
 * Go HTTP Server Template API
 * Go HTTP Server Template API
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Organization
 * @export
 * @interface Organization
 */
export interface Organization {
    /**
     * Organization ID
     * @type {string}
     * @memberof Organization
     */
    'id': string;
    /**
     * Organization の名前
     * @type {string}
     * @memberof Organization
     */
    'name': string;
}

