/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * パスワード再設定リクエスト
 * @export
 * @interface ResetPasswordRequest
 */
export interface ResetPasswordRequest {
    /**
     * 新しく設定するパスワード
     * @type {string}
     * @memberof ResetPasswordRequest
     */
    'new_password': string;
    /**
     * 
     * @type {string}
     * @memberof ResetPasswordRequest
     */
    'reset_token': string;
}

