/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InsuranceContractor } from './insurance-contractor';

/**
 * 保険契約者情報検索レスポンス
 * @export
 * @interface SearchInsuranceContractorResponse
 */
export interface SearchInsuranceContractorResponse {
    /**
     * 検索条件に該当する保険契約者情報の配列
     * @type {Array<InsuranceContractor>}
     * @memberof SearchInsuranceContractorResponse
     */
    'insurance_contractors'?: Array<InsuranceContractor>;
    /**
     * 合計ページ数
     * @type {number}
     * @memberof SearchInsuranceContractorResponse
     */
    'total_page'?: number;
    /**
     * 合計要素数
     * @type {number}
     * @memberof SearchInsuranceContractorResponse
     */
    'total_num'?: number;
    /**
     * 現在ページ
     * @type {number}
     * @memberof SearchInsuranceContractorResponse
     */
    'current_page'?: number;
}

