/* tslint:disable */
/* eslint-disable */
/**
 * HARUTO COATIONG API
 * HARUTO COATIONG API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 契約者メモ更新リクエスト
 * @export
 * @interface UpdateInsuranceContractorsMemoRequest
 */
export interface UpdateInsuranceContractorsMemoRequest {
    /**
     * 更新後のメモ内容
     * @type {string}
     * @memberof UpdateInsuranceContractorsMemoRequest
     */
    'memo'?: string;
}

