root = "."
tmp_dir = "./src/tmp"

[build]
  bin = "./src/tmp/main"
  cmd = "cd ./src && go build -o ./tmp/main ./cmd/serve/main.go"
  delay = 2000
  exclude_dir = ["terraform", "proto", ".github", "docker", "doc", ".github"]
  exclude_file = ["docker-compose.yml", "docker-compose.env", "Makefile", "README.md"]
  exclude_regex = []
  exclude_unchanged = false
  follow_symlink = false
  full_bin = ""
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]
  kill_delay = 500
  log = "build-errors.log"
  send_interrupt = false
  stop_on_error = true

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[log]
  time = false

[misc]
  clean_on_exit = true
