FROM alpine:3.13.3

RUN apk --update add tzdata && \
    cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime && \
    apk del tzdata && \
    rm -rf /var/cache/apk/*

RUN mkdir -p /go/src/github.com/myuoncorp/go-http-server-template/bin
WORKDIR /go/src/github.com/myuoncorp/go-http-server-template/bin

ADD ./build/go-http-server-template /go/src/github.com/myuoncorp/go-http-server-template/bin

RUN ls /go/src/github.com/myuoncorp/go-http-server-template/bin

EXPOSE 8080
ENTRYPOINT /go/src/github.com/myuoncorp/go-http-server-template/bin/go-http-server-template
