/* tslint:disable */
/* eslint-disable */
/**
 * TEMPLATE API
 * TEMPLATE API Interface
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
/**
 * HealthckeckApi - axios parameter creator
 * @export
 */
export const HealthckeckApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * for health ckeck 
         * @summary health ckeck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthckeckApi - functional programming interface
 * @export
 */
export const HealthckeckApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthckeckApiAxiosParamCreator(configuration)
    return {
        /**
         * for health ckeck 
         * @summary health ckeck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * HealthckeckApi - factory interface
 * @export
 */
export const HealthckeckApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthckeckApiFp(configuration)
    return {
        /**
         * for health ckeck 
         * @summary health ckeck
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: any): AxiosPromise<void> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthckeckApi - object-oriented interface
 * @export
 * @class HealthckeckApi
 * @extends {BaseAPI}
 */
export class HealthckeckApi extends BaseAPI {
    /**
     * for health ckeck 
     * @summary health ckeck
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthckeckApi
     */
    public healthCheck(options?: AxiosRequestConfig) {
        return HealthckeckApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}
